import React, { useLayoutEffect } from 'react'

function UseLayoutEffect() {
    /* BOTH USEEFFECT AND USELAYOUTEFFECT ARE SAME 
    BUT THE MAJOR DIFFERENCE BETWEEN THEM IS IN TIMING OF EXECUTION.

    WHERE USE EFFECT RUNS AFTER THE DOM GETS UPDATED AND THE BROWSER GETS PAINTED,
    SO IN THIS THE SIDE EFFECTS ARE NOT SEE IN UI IMMEADIATLY.
    USEEFFFECT RUNS ASYNCHRONOUSLY,SO IT DOES NOT BLOCK THE BROWSER PAINTING PROCESS,

    WHERE USELAYOUTEFFECT IS EXECUTED DURING THE DOM UPDATION SO THIS RUNS BEFORE THE 
    BROWSER PAITING PROCESS,SO SIDE EFFECTS ARE SEE IMMEADIATLY IN THIS HOOK.
    USELAYOUTEFFECT RUNS SYNCHRONOUSLY SO THIS BLOCKS THE BROWSER PAINTING PROCESS AND GETS EXECUTED.*/

    useLayoutEffect(()=>{

    },[])
  return (
    <div>
        <h1>USELAYOUTEFFECT HOOK</h1>
    </div>
  )
}

export default UseLayoutEffect